# Generated by Django 5.2.17 on 2026-10-01 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nume Departament')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Cod Structură / Piese')),
                ('name', models.CharField(max_length=150, verbose_name='Denumire Material')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stoc Curent')),
                ('minimum_limit', models.IntegerField(default=5, verbose_name='Prag Minim Alertă')),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.IntegerField(verbose_name='Cantitate Cerută')),
                ('status', models.CharField(choices=[('PENDING', 'În așteptare'), ('APPROVED', 'Aprobată'), ('REJECTED', 'Respinsă')], default='PENDING', max_length=20, verbose_name='Status Cerere')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creării')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.department', verbose_name='Departament Solicitant')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material', verbose_name='Material Cerut')),
            ],
        ),
    ]
