# Generated by Django 5.2.17 on 2026-10-04 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Cod Utilaj / Linie')),
                ('name', models.CharField(max_length=150, verbose_name='Denumire Echipament')),
                ('location', models.CharField(max_length=100, verbose_name='Locație / Hală')),
            ],
        ),
        migrations.AddField(
            model_name='requisition',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.equipment', verbose_name='Utilaj / Echipament Defect'),
        ),
    ]
