# Generated by Django 5.2.17 on 2026-10-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_equipment_requisition_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_running',
            field=models.BooleanField(default=True, verbose_name='Utilaj Pornit / Funcțional'),
        ),
    ]
