# Generated by Django 5.2.17 on 2026-10-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_equipment_is_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cod / Descriere Eroare PLC'),
        ),
    ]
